### ISSUE TITLE
无法复现。

### ISSUE THREAD

**Issue by Linzsd** [huanranchen/ASRNorm#1]
您好，请问您是如何训练的呢，我在PACS数据集上，训练不起来，如果方便的话，您可以开源训练代码吗，或者一些训练细节，谢谢

**Comment by huanranchen** [comment]
这个不是官方代码，我也只是自己写写...不过我会补充训练代码的

**Comment by huanranchen** [comment]
我们也会在一个月内补充在PACS上的训练代码和训练结果。

**Comment by huanranchen** [comment]
已补充，详见Solver.py
